### ISSUE TITLE
Fatal error in logs

### ISSUE THREAD

**Issue by TheRealWaldo** [TheRealWaldo/ha-optimal-humidity#40]
## Version of the custom_component

1.3.9
## Configuration

Any

## Describe the bug

Fatal error in logs

## Debug log

```text

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/optimal_humidity/sensor.py:597
Integration: optimal_humidity (documentation, issues)
First occurred: 4:40:59 PM (28 occurrences)
Last logged: 6:49:28 PM

Update for sensor.bathroom_optimal_humidity fails
Update for sensor.living_room_optimal_humidity fails
Update for sensor.kitchen_optimal_humidity fails
Update for sensor.basement_optimal_humidity fails
Update for sensor.master_bedroom_optimal_humidity fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/config/custom_components/optimal_humidity/sensor.py", line 408, in async_update
    self._calc_optimal_humidex()
  File "/config/custom_components/optimal_humidity/sensor.py", line 597, in _calc_optimal_humidex
    optimal_humidex = self._humidex(self._indoor_temp, self._optimal_humidity / 100)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'


```

**Comment by TheRealWaldo** [comment]
Not fixed in all cases.
